print("\n")
print("Enter two integral numbers to perform operations: ")
num1 = int(input())
num2 = int(input())
print("\n")
print("Addition of given numbers: ", num1+num2)
print("Subtraction of given numbers: ", num1-num2)
print("Multiplication of given numbers: ", num1*num2)
print("Division of given numbers: ", num1/num2)
print("Modulo Division of given numbers: ", num1%num2)
print("Floor Division of given numbers: ", num1//num2)
print("\n")
print("\n")
