print("\n")
print("\n")

print("Enter two float numbers to perform operations: ")
num1 = float(input())
num2 = float(input())
print("Addition of given numbers: ", num1+num2)
print("Subtraction of given numbers: %0.2f" %(num1-num2))
print("Multiplication of given numbers: ", num1*num2)
print("Division of given numbers: ", num1/num2)
print("Floor Division of given numbers: ", num1//num2)
print("\n")
print("\n")