print("\n")
print("\n")

print("Enter three numbers to perform relational operators on them: ")
num1 = int(input())
num2 = int(input())
num3 = int(input())
print("\n")
print("performing relational operation")
print(num1,">",num2,"is: ",num1>num2)
print(num1,"<",num2,"is: ",num1<num2)
print(num3,">=",num2,"is: ",num3>=num2)
print(num1,"<=",num2,"is: ",num1<=num2)
print(num1,"!=",num3,"is: ",num1!=num3)
print(num1,"==",num2,"is: ",num2==num3)
print("\n")
print("\n")